### ISSUE TITLE
Translation for german graphics

### ISSUE THREAD

**Issue by Gabbalo** [circumspect/White-Rabbit#101]
Hi everyone,
if someone have a handy walk through on how to translate the cards/posters in an easy way, I'll happily spend my holidays on translate those as well :) Until now, I did not find an easy way to do this without not having the right fonts/colors to edit the graphics in paint.net or something.

Greetz, Hati

**Comment by circumspect** [comment]
Hi,
If you look in /resources/images/templates/ you should find Krita templates for most of the card types (the clue card template seems to be missing, maybe @Ylkhana has it?). All you need to do is copy the /resources/images/en/ directory, open each template file in Krita and modify the text, then export each one to a .png and replace the files in the new directory. The location cards are also missing templates, as it is a bit more difficult to make those without the original background art or better photoshop skills than I currently have.

The two main fonts used in the original cards (as far as I can tell) are DIN Condensed and Built Titling. You can find these in the /resources/fonts/ folder.

**Comment by circumspect** [comment]
For the motivation cards, you might have to cover up the parts that say "Motivation" and "Relations" before you write new text over them. I think the font for those parts is Built Titling Regular, which is the `built titling rg.ttf` file in the fonts folder.

**Comment by Gabbalo** [comment]
I have translated the introduction, debrief, motivation cards and the search-cards so far. For everything else, the template is missing. Maybe I'll be able to create the character-cards from the intro-template.
I had to be creative in the translation to not only fit the context but the space, too. Forgive me on that.

**Comment by circumspect** [comment]
No worries! Thanks for helping translate :)
