### ISSUE TITLE
Fixing Missing Glyph issue

### ISSUE THREAD

**Issue by PanopticaRising** [circumspect/White-Rabbit#103]
Hey all. Just documenting this. One of my players popped an emoji in DM and it broke the PDF export. I was able to fix it by adding the following line:

```
@@ -682,6 +699,9 @@ class Export(commands.Cog):
                 continue

             line = f"{author}: {line}"
+            line = line.encode("ascii", "ignore").decode()
```

Thanks for the great bot! It worked super well. The only surprise was that it included the "turn the lights off" card, which I wasn't expecting my group to get.

**Comment by circumspect** [comment]
Hi,
Thank you for your feedback! Which version of the bot were you using? The latest version on the releases page, or something else?

**Comment by PanopticaRising** [comment]
I think I was using the image on dockerhub (0.10.2?) to run the game, but I still couldn't export with 0.10.3 either.

**Comment by circumspect** [comment]
I tested the proposed fix, and unfortunately it would also remove characters such as the French `ç`. As a result, I'm closing this issue as the missing glyph warnings don't impact the bot's functionality.
