### ISSUE TITLE
RuntimeWarning error when launching, and commands not found

### ISSUE THREAD

**Issue by vyder** [circumspect/White-Rabbit#109]
When the bot is launched (both via docker, or by running a local instance), I get the following error:

```
❯ docker logs white-rabbit
/whiterabbit/./src/__main__.py:140: RuntimeWarning: coroutine 'BotBase.load_extension' was never awaited
  bot.load_extension(plugin)
RuntimeWarning: Enable tracemalloc to get the object allocation traceback
[2022-08-26 17:12:12] [INFO    ] discord.client: logging in using static token
[2022-08-26 17:12:13] [INFO    ] discord.gateway: Shard ID None has connected to Gateway (Session ID: 6efbe840f29d229fea2998806d05fd23).
```

The bot does connect to the discord server, however, any attempt to enter commands in #bot-channel results in a `Command not found!` message. `!help` is the only command that seems to be available, and it prints this:

```
​No Category:
  help Shows this message

Type !help command for more info on a command.
You can also type !help category for more info on a category.
```

I don't do enough python dev to be able to debug specifically what's going on.

---

The steps I have taken to run the bot is:
1. Clone the repo
2. Copy example.env to .env
3. `docker build -t white-rabbit .`
4. `docker run -d --name=white-rabbit --env TOKEN=[redacted] --restart unless-stopped white-rabbit`
5. `docker logs white-rabbit`

I was also getting a FileNotFoundError, but I set `USE_LOCAL_IMAGES` to true in my `.env` to bypass that

```
FileNotFoundError: https://raw.githubusercontent.com/circumspect/White-Rabbit/0.12.0/images/en/player-resources/Guide
```

**Comment by circumspect** [comment]
Hi,
Are you using discord.py v2? I don't think the bot has been migrated yet

**Comment by circumspect** [comment]
It seems like cog loading is async in v2:
https://discordpy.readthedocs.io/en/stable/migrating.html#command-extension-changes

**Comment by circumspect** [comment]
Updated the `requirements.txt` in 0.12.1
