### ISSUE TITLE
Bot Logs In but doesn't obey to commands

### ISSUE THREAD

**Issue by Ghuldrigan** [circumspect/White-Rabbit#111]
Hi. I just tried to set a game of AIM, downloaded and installed last version of The White Bot (as in 0.12.1) and I've managed to make it come online at Discord but It won't obey any command; not even !help

We tried as well with "/" + command, didn't work either.

Thank you so much for your kind efforts.

**Comment by maxafin** [comment]
Having the same issue, bot logs in fine but then wont respond after that.

**Comment by pipejakob** [comment]
Could either of you try enabling the "Message Content Intent" for your bot as proposed in https://github.com/circumspect/White-Rabbit/pull/112 to see if it fixes your issue?

![message_content_intent](https://user-images.githubusercontent.com/1605981/193478329-ca63f28f-bb0b-473f-a651-cdb3cf18399d.jpg)

**Comment by circumspect** [comment]
The above seems to fix this issue, but I'll leave this open for a week or until someone else confirms that it solves it for them.

**Comment by circumspect** [comment]
@all-contributors add @Ghuldrigan for bugs

**Comment by Ghuldrigan** [comment]
Hi. I could finally try it and It works with the above mentioned. Sorry for not reading #112 before.
