### ISSUE TITLE
Trying to run the bot on a Raspberry Pi 4

### ISSUE THREAD

**Issue by Leujii** [circumspect/White-Rabbit#126]
**Description**
running the code locally, and getting this error : 
python src
Traceback (most recent call last):
  File "/usr/lib/python3.9/runpy.py", line 197, in _run_module_as_main
    return _run_code(code, main_globals, None,
  File "/usr/lib/python3.9/runpy.py", line 87, in _run_code
    exec(code, run_globals)
  File "/home/pi/alice_is_missing/White-Rabbit-0.12.5/src/__main__.py", line 13, in <module>
    from debug import DEBUG_COMMAND_LIST
  File "/home/pi/alice_is_missing/White-Rabbit-0.12.5/src/debug.py", line 7, in <module>
    import filepaths
  File "/home/pi/alice_is_missing/White-Rabbit-0.12.5/src/filepaths.py", line 2, in <module>
    import dirs
  File "/home/pi/alice_is_missing/White-Rabbit-0.12.5/src/dirs.py", line 4, in <module>
    from localization import DEFAULT_LOCALIZATION, LANGUAGE_KEY
  File "/home/pi/alice_is_missing/White-Rabbit-0.12.5/src/localization.py", line 23, in <module>
    localization_file = LOCALIZATION_DIR / LOCALIZATIONS[LANGUAGE_KEY]
KeyError: 'fr_FR.UTF-8'

**Reproducing**
1. install the bot locally by unzipping on a raspberry 4 Pi, distribution bullseye
2. run the requirements download from requirements.txt
3. run the code with python src/ (from main folder). Note that i made sure python 3 is running instead of python 2

**Expected behavior**
the bot runs smoothly

**System Info**
OS: Raspbian Bullseye
Python version: 3.9
Bot version: 0.12.5

**Other details**
I tried to run it through docker as well, but the errors are not verbose enough to get it to work as well. Probably the same error occurs, but the error code is just invalid format.
I changed the platform to force a run on linux/amd64 as well.
I tried to change the language from 'fr' to 'en', got the same result

**Comment by circumspect** [comment]
Can you try changing line 21 in ``localization.py`` ([this one](https://github.com/circumspect/White-Rabbit/blob/main/src/localization.py#L21)) from

```py
LANGUAGE_KEY = envvars.get_env_var("LANGUAGE")
```

to 

```py
LANGUAGE_KEY = "en"
```

and see if that changes anything?

**Comment by Leujii** [comment]
That works as is ! Can i switch it to french as well with the same trick ? 

Thanks a lot for the very quick reply ! ;)

**Comment by circumspect** [comment]
You should be able to, yes! I suspect the pi has an environment variable called `LANGUAGE` which is causing the bot to trip up - I'll change the name of the variable the bot looks for in the next patch to avoid this happening in the future. Thanks for the report!

**Comment by circumspect** [comment]
Fixed in 0.13.0

**Comment by Leujii** [comment]
Yup that must be something like that indeed. That should fix the docker run as well 
Thanks a lot for the help ! ;)

**Comment by Leujii** [comment]
although, when switching to french it seems that it cannot reach the guide. Here is the debug log : 
Loading localization data (fr)... Done!
Traceback (most recent call last):
  File "/home/pi/alice_is_missing/White-Rabbit-0.12.5/src/utils.py", line 102, in get_image
    return find_url(localized_url, ImageResource.IMAGE_EXTENSIONS)
  File "/home/pi/alice_is_missing/White-Rabbit-0.12.5/src/utils.py", line 78, in find_url
    raise FileNotFoundError(url)
FileNotFoundError: https://raw.githubusercontent.com/circumspect/White-Rabbit/0.12.5/resources/images/fr/player-resources/Guide

**Comment by circumspect** [comment]
Sorry! I was updating some tags and temporarily deleted 0.13.0. It should work now, though

**Comment by Leujii** [comment]
Yup ! That works now in french as well for the local running ! Thanks a lot

**Comment by circumspect** [comment]
So I messed up the repo and need to fix some things, but if you need to run the bot in the next little bit you can also use the `WHITE_RABBIT_USE_LOCAL_IMAGES` environment variable to force the bot to use the locally saved images. By default the bot pulls the images from Github and only sends the links to make sending them faster.

**Comment by Leujii** [comment]
yup don't worry, i can adapt since i have full control over the Pi anyway ! Also, the docker on 0.13.0 still returns the same error, and if you need testers for that i'd be happy to help ;) For now the local version runs well and that's all good on my side
Thanks a lot !

**Comment by circumspect** [comment]
Okay, I think I fixed the issues I was having with the repo. Let me know if you run into any other issues!

**Comment by circumspect** [comment]
@all-contributors add @Leujii for bug
