### ISSUE TITLE
Files missing?

### ISSUE THREAD

**Issue by Sinesthesyc** [circumspect/White-Rabbit#141]
Sorry to bother you. I'm working on the Spanish translation but when it comes to cards I can't find some .kra files. Like the ones for the clue or characters cards. Is there only the png file available for those? 

Thank u.

Edit: Introduction.template file has a non-editable french text.

**Comment by Sinesthesyc** [comment]
Nevermind, I tweaked them myself. Except for the Introduction.template. Can you update that file without the text, please?

**Comment by circumspect** [comment]
Hi,
Most of the templates you see were created by other people (thanks @Ylkhana!). As a result, there are currently some images for which there are no templates available, as I either haven't had the time or don't personally have the skills necessary to clean up the images and create the templates. I can see about getting the introduction template fixed, but I can't guarantee if or when it will be done. In the meantime, feel free to add or update any .kra files if you find missing parts! Sorry about the inconvenience, and thanks again for your work on translating the bot and game.

**Comment by circumspect** [comment]
@all-contributors add @Sinesthesyc for translation

**Comment by Sinesthesyc** [comment]
I made the introduction template myself, don't worry. I'll upload the .kra file soon.
