### ISSUE TITLE
TypeError: Population must be a sequence.

### ISSUE THREAD

**Issue by dracek1458** [circumspect/White-Rabbit#148]
**Description**
Hello,
after I try to run the bot I keep getting error message about line 52 in card.py file (Log in Other details). It's a fresh download, just added Bot Token, nothing is altered (Not a Python guy).

**Reproducing**
1. Run the bot
2. See error

**Expected behavior**
Run the bot

**System Info**
OS: Win10
Python version: 3.11.2
Bot version: 0.14.1

**Other details**
Traceback (most recent call last):
  File "<frozen runpy>", line 198, in _run_module_as_main
  File "<frozen runpy>", line 88, in _run_code
  File "C:\WR\src\__main__.py", line 12, in <module>
    from cogs.debug import DEBUG_COMMAND_LIST
  File "C:\WR\src\cogs\debug.py", line 7, in <module>
    from data import filepaths, gamedata
  File "C:\WR\src\data\filepaths.py", line 1, in <module>
    from data import cards, dirs
  File "C:\WR\src\data\cards.py", line 52, in <module>
    suspect_keys = random.sample(ALL_SUSPECTS.keys(), 5)
                   ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
  File "C:\Users\Matej\AppData\Local\Programs\Python\Python311\Lib\random.py", line 439, in sample
    raise TypeError("Population must be a sequence.  "
TypeError: Population must be a sequence.  For dicts or sets, use sorted(d).

**Comment by circumspect** [comment]
It looks like this is a recent change in Python - running a minimal example to replicate this gives me a DeprecationWarning. Can you try changing that line to
```py
suspect_keys = random.sample(list(ALL_SUSPECTS), 5)
```
and see if that fixes it?

**Comment by dracek1458** [comment]
Great! That fixed it!
Same problem was on the line 56, so
```python
location_keys = random.sample(ALL_LOCATIONS.keys(), 5)
```
had to be changet to
```python
location_keys = random.sample(list(ALL_LOCATIONS), 5)
```

**Comment by circumspect** [comment]
Okay! I'll make the changes and push a new release then. Thanks for the report!

**Comment by circumspect** [comment]
@allcontributors add @dracek1458 for bug
