### ISSUE TITLE
Command for wiping game channels only

### ISSUE THREAD

**Issue by WagagaCZ** [circumspect/White-Rabbit#151]
Hi!

!wipe currently wipes all channels on the server. Would be possible to add command that erases only the game channels (The Game and Text category)?

**Comment by circumspect** [comment]
Hi,
Sorry, could you explain why you would like this added? I'm not clear on what the benefit of this would be, since usually if you want to keep the messages you'd want to keep the clues and other cards as well.

**Comment by WagagaCZ** [comment]
I have a server with few friends where I run your bot. In OOC they usually planning next games, sharing PDFs etc and when I reset or wipe server it removes the OOC chats as well.

**Comment by circumspect** [comment]
Hmm, okay. I'll look into allowing category names as an argument to !wipe when I have the chance (I believe it already supports single channel names?), but if you're looking for something sooner it shouldn't be too difficult to implement it yourself. Thanks for the feedback!

**Comment by circumspect** [comment]
Oh, and thanks for sponsoring me! It means a lot that you enjoyed using the bot so much <3

**Comment by WagagaCZ** [comment]
It's a worthy investment! We use your bot pretty regularly + we run our "modded" Harry Potter themed Alice with your bot, so those dollars are deserved <3

**Comment by circumspect** [comment]
Added in 0.14.3! You can find the updated documentation [here](https://white-rabbit.readthedocs.io/en/latest/user-guide/admin.html#resetting-the-server).

Oh that's super cool! Have you tried out the support for custom cards released in 0.14.0? I would love to hear your feedback on it, especially with the new expansion coming out.

**Comment by WagagaCZ** [comment]
Not yet. This "mod" was done on the 0.11.0 but I'm planning on reedoing it on this new system!
