### ISSUE TITLE
Auto-PDF Upload review

### ISSUE THREAD

**Issue by Gabbalo** [circumspect/White-Rabbit#166]
**Description**
With Discord being more generous, direct upload could be possible

**Other details**

> Note that because Discord limits file uploads to 8MB and the generated files are ~25MB in size, there is no way for the bot to send the PDF files directly via Discord.

Discord recently announced (I cannot check if they implemented it, because Nitro ;) ) to increase the file size limit to 25MB.
With the log-export being **around** that size, maybe a if-switch could be implemented to directly upload the file if it's like 24.5MB in size (margin! :D ) or less and if it's larger, go to the current supply mechanism. And if they ever lift the size again, just increase the variable and never be bothered to manually upload it again :)

Since this is a suggestion for improv, I spare you the other details requested for an issue ;)

**Comment by circumspect** [comment]
Done in 0.16.0
