### ISSUE TITLE
Add support for new characters

### ISSUE THREAD

**Issue by circumspect** [circumspect/White-Rabbit#62]

**Comment by Ylkhana** [comment]
Maybe consequently add a command to change localization data in .env file instead of having to manually change it everytime ?

**Comment by stephenkilpatrick** [comment]
Is this a feature for adding new localization characters? Or new playable characters? Because that second one? I'm all about that. I'm sure I could help draft up a few additional PCs to mix up the game a bit.

**Comment by circumspect** [comment]
It would be new playable characters. The main difficulty here is that implementing this requires a fair amount of work. Off the top of my head:

- Localization would have to be reworked a bit to allow for arbitrary character names, probably using placeholder strings like $NAME$ or something similar.
- The bot would need to create new channels for each character added to the game, probably through a command like `!addchar Riley`. This would also require creating new roles and setting permissions correspondingly.

**Comment by stephenkilpatrick** [comment]
Timing of this is interesting. After our successful game on Sunday, I had some conversation about changing setting and characters, and thought about the modularity of white-rabbit. I think that conversation fell apart after it seemed like the very specific genre of Alice is Missing fits the form of the game really well. Hard to imagine a cyberpunk or scifi game so well dialed in for text messaging.

**Comment by circumspect** [comment]
Bumping this issue because an expansion pack is in the works:

https://www.polygon.com/23577920/alice-is-missing-expansion-silent-falls-spenser-starke-interview

**Comment by circumspect** [comment]
Current status: the bot can find and use additional cards for the following:
- suspects
- locations
- searching cards

To use these cards, add the files to the `resources` folder in the appropriate locations, then make a copy of `base.yaml` in `card_lists` and add the relevant entries. Finally, set `WHITE_RABBIT_USE_LOCAL_IMAGES` to true, and set `WHITE_RABBIT_CARD_LIST` to the name of your file, without the .yaml extension.

The bot should also be able to find new character cards, but the ability to play with them is blocked on #121.

**Comment by circumspect** [comment]
Closing this issue as custom character cards are supported in the latest commit. The format for the custom card lists will likely change before the 0.14.0 release though, especially as I still need to implement support for new clues.
