### ISSUE TITLE
French PDF export broken

### ISSUE THREAD

**Issue by Ylkhana** [circumspect/White-Rabbit#66]
Switched bot to french
Corrected a couple case issues (see PR)
Tried !pdf on my server 
Got unknown error message, logs as follow :

> Traceback (most recent call last):
>   File "/whiterabbit/./src/utils.py", line 46, in get_image
>     return img.get(directory, name)
>   File "/whiterabbit/./src/resources.py", line 24, in get
>     raise FileNotFoundError(directory / name)
> FileNotFoundError: /whiterabbit/resources/images/fr/posters/Alice-Briarwood-0
> 
> During handling of the above exception, another exception occurred:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 85, in wrapped
>     ret = await coro(*args, **kwargs)
>   File "/whiterabbit/./src/export.py", line 391, in pdf
>     poster = utils.get_image(constants.POSTER_DIR, f"Alice-Briarwood-{ctx.game.alice}")
>   File "/whiterabbit/./src/utils.py", line 52, in get_image
>     return img.get(Path(join(*parts)), name)
>   File "/whiterabbit/./src/resources.py", line 24, in get
>     raise FileNotFoundError(directory / name)
> FileNotFoundError: /whiterabbit/resources/images/en/posters/Alice-Briarwood-0
> 
> The above exception was the direct cause of the following exception:
> 
> Traceback (most recent call last):
>   File "/usr/local/lib/python3.9/site-packages/discord/client.py", line 343, in _run_event
>     await coro(*args, **kwargs)
>   File "/whiterabbit/./src/__main__.py", line 116, in on_command_error
>     raise error
>   File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/bot.py", line 902, in invoke
>     await ctx.command.invoke(ctx)
>   File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 864, in invoke
>     await injected(*ctx.args, **ctx.kwargs)
>   File "/usr/local/lib/python3.9/site-packages/discord/ext/commands/core.py", line 94, in wrapped
>     raise CommandInvokeError(exc) from exc
> discord.ext.commands.errors.CommandInvokeError: Command raised an exception: FileNotFoundError: /whiterabbit/resources/images/en/posters/Alice-Briarwood-0

**Comment by circumspect** [comment]
I think this is fixed in 0.8.2 after merging, so I'm going to close this. Thanks for catching it!

**Comment by Ylkhana** [comment]
The problem still exists as of 0.8.3 :(
