### ISSUE TITLE
[Improvement] !wipe and !reset affecting only game channels

### ISSUE THREAD

**Issue by Ylkhana** [circumspect/White-Rabbit#78]
As per title, an idea that would help the bot being used on bigger RPG-related Discord channels, and even help supporting successive games on a single channel.

As for now, when you use !wipe or !reset, the whole server is concerned. Thought it would be neat if the discussion zone (and maybe a few channels related to archives or organization, if you want to share exported PDFs or use a doodle to setup your game) was spared by that cleaning. 
--> Maybe manage that by adding a "tag" before the channel's name (e.g. IRL-discussions, IRL-orga) that would exclude these channels from the command ? idk if that's hard/possible, sorry !

**Comment by circumspect** [comment]
If you tag channels when calling !wipe you can choose which channels you want to erase, e.g. !wipe #bot-channel #discussion. I'll add that to the documentation, sorry about that!

**Comment by circumspect** [comment]
As for reset, it calls `!reset_perms` to reset the channel permissions, and `!wipe` to erase messages. It also clears all nicknames and all roles from everyone but the server owner, though this can be split off into a separate command that then gets called as well (will need to be updated to only remove character roles though)

**Comment by circumspect** [comment]
There is now a separate command to remove character roles from the players, (`!reset` now calls this, but its behavior should be the same as before). If there's anything else related to this issue please let me know, otherwise I'll close it in a few days
