### ISSUE TITLE
Failure to start with directories not named "White-Rabbit"

### ISSUE THREAD

**Issue by Zanaku** [circumspect/White-Rabbit#90]
Hello!

This is really more of a documentation thing - at the moment the docs say "Download the source zip from Github here and extract the files to a directory of your choice.", which I did, using the default folder name from the zip file, which is 'White-Rabbit-0.9.4'.

Unfortunately, the bot fails to start, and I was able to narrow it down to rabbit_path in utils.py, where it checks for directories named exactly "White-Rabbit".

As such, I think it'd be useful to update the docs to specify the folder name explicitly, in case anyone else tries it with this versioned folder name.

Cheers for the hard work!

**Comment by circumspect** [comment]
Ah that's a bug, it should be fixed in the latest release (0.9.5). You can name the folder whatever you'd like. Thanks for reporting it!

**Comment by circumspect** [comment]
@all-contributors please add @Zanaku for bug reports
