### ISSUE TITLE
Open until closed

### ISSUE THREAD

**Issue by Gabbalo** [circumspect/White-Rabbit#93]
Is there any chance to get the bot to the background as a service or something like that?
Currently, you have to log in to your server and stay there until the game is closed. 
Thats fine, if the server admin is one of the players. But it's a pain, if not.

**Comment by circumspect** [comment]
If you look up "free discord bot hosting" there are several sites that offer pretty much exactly that, though I haven't tried any of them

**Comment by circumspect** [comment]
Closing this issue as it isn't really something that could be fixed by changing the bot
